package com.xiaoweixin.dto;

import java.util.Date;

public class TDictData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_data.id
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_data.dict_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String dictNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_data.dictdata_value
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String dictdataValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_data.dictdata_name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String dictdataName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_data.is_fixed
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Integer isFixed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_data.order_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_data.description
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_data.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_data.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_data.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_data.id
     *
     * @return the value of t_dict_data.id
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_data.id
     *
     * @param id the value for t_dict_data.id
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_data.dict_no
     *
     * @return the value of t_dict_data.dict_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getDictNo() {
        return dictNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_data.dict_no
     *
     * @param dictNo the value for t_dict_data.dict_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setDictNo(String dictNo) {
        this.dictNo = dictNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_data.dictdata_value
     *
     * @return the value of t_dict_data.dictdata_value
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getDictdataValue() {
        return dictdataValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_data.dictdata_value
     *
     * @param dictdataValue the value for t_dict_data.dictdata_value
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setDictdataValue(String dictdataValue) {
        this.dictdataValue = dictdataValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_data.dictdata_name
     *
     * @return the value of t_dict_data.dictdata_name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getDictdataName() {
        return dictdataName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_data.dictdata_name
     *
     * @param dictdataName the value for t_dict_data.dictdata_name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setDictdataName(String dictdataName) {
        this.dictdataName = dictdataName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_data.is_fixed
     *
     * @return the value of t_dict_data.is_fixed
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Integer getIsFixed() {
        return isFixed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_data.is_fixed
     *
     * @param isFixed the value for t_dict_data.is_fixed
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setIsFixed(Integer isFixed) {
        this.isFixed = isFixed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_data.order_no
     *
     * @return the value of t_dict_data.order_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_data.order_no
     *
     * @param orderNo the value for t_dict_data.order_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_data.description
     *
     * @return the value of t_dict_data.description
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_data.description
     *
     * @param description the value for t_dict_data.description
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_data.create_time
     *
     * @return the value of t_dict_data.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_data.create_time
     *
     * @param createTime the value for t_dict_data.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_data.modify_time
     *
     * @return the value of t_dict_data.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_data.modify_time
     *
     * @param modifyTime the value for t_dict_data.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_data.is_del
     *
     * @return the value of t_dict_data.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_data.is_del
     *
     * @param isDel the value for t_dict_data.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}