package com.xiaoweixin.dto;

public class TFriend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.user_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.friend_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String friendNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.no
     *
     * @return the value of t_friend.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.no
     *
     * @param no the value for t_friend.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.user_no
     *
     * @return the value of t_friend.user_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.user_no
     *
     * @param userNo the value for t_friend.user_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.friend_no
     *
     * @return the value of t_friend.friend_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getFriendNo() {
        return friendNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.friend_no
     *
     * @param friendNo the value for t_friend.friend_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setFriendNo(String friendNo) {
        this.friendNo = friendNo;
    }
}