package com.xiaoweixin.dto;

import java.util.Date;

public class TMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.p_menu_code
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String pMenuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.level
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.url
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.icon
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.is_menu
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Integer isMenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.order_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.no
     *
     * @return the value of t_menu.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.no
     *
     * @param no the value for t_menu.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_name
     *
     * @return the value of t_menu.menu_name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.menu_name
     *
     * @param menuName the value for t_menu.menu_name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.p_menu_code
     *
     * @return the value of t_menu.p_menu_code
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getpMenuCode() {
        return pMenuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.p_menu_code
     *
     * @param pMenuCode the value for t_menu.p_menu_code
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setpMenuCode(String pMenuCode) {
        this.pMenuCode = pMenuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.level
     *
     * @return the value of t_menu.level
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.level
     *
     * @param level the value for t_menu.level
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.url
     *
     * @return the value of t_menu.url
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.url
     *
     * @param url the value for t_menu.url
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.icon
     *
     * @return the value of t_menu.icon
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.icon
     *
     * @param icon the value for t_menu.icon
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.is_menu
     *
     * @return the value of t_menu.is_menu
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Integer getIsMenu() {
        return isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.is_menu
     *
     * @param isMenu the value for t_menu.is_menu
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setIsMenu(Integer isMenu) {
        this.isMenu = isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.order_no
     *
     * @return the value of t_menu.order_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.order_no
     *
     * @param orderNo the value for t_menu.order_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.create_time
     *
     * @return the value of t_menu.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.create_time
     *
     * @param createTime the value for t_menu.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.modify_time
     *
     * @return the value of t_menu.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.modify_time
     *
     * @param modifyTime the value for t_menu.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.is_del
     *
     * @return the value of t_menu.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.is_del
     *
     * @param isDel the value for t_menu.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}