package com.xiaoweixin.dto;

import java.util.Date;

public class TOrg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.p_org_code
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String pOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.org_name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.icon
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.order_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.decription
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String decription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_org.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.no
     *
     * @return the value of t_org.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.no
     *
     * @param no the value for t_org.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.p_org_code
     *
     * @return the value of t_org.p_org_code
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getpOrgCode() {
        return pOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.p_org_code
     *
     * @param pOrgCode the value for t_org.p_org_code
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setpOrgCode(String pOrgCode) {
        this.pOrgCode = pOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.org_name
     *
     * @return the value of t_org.org_name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.org_name
     *
     * @param orgName the value for t_org.org_name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.icon
     *
     * @return the value of t_org.icon
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.icon
     *
     * @param icon the value for t_org.icon
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.order_no
     *
     * @return the value of t_org.order_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.order_no
     *
     * @param orderNo the value for t_org.order_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.decription
     *
     * @return the value of t_org.decription
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getDecription() {
        return decription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.decription
     *
     * @param decription the value for t_org.decription
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setDecription(String decription) {
        this.decription = decription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.create_time
     *
     * @return the value of t_org.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.create_time
     *
     * @param createTime the value for t_org.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.modify_time
     *
     * @return the value of t_org.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.modify_time
     *
     * @param modifyTime the value for t_org.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_org.is_del
     *
     * @return the value of t_org.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_org.is_del
     *
     * @param isDel the value for t_org.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}