package com.xiaoweixin.dto;

public class TQr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qr.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qr.qr_url
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String qrUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qr.qr_describe
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String qrDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qr.age_range
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String ageRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qr.user_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qr.disennable
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String disennable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qr.sex
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qr.no
     *
     * @return the value of t_qr.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qr.no
     *
     * @param no the value for t_qr.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qr.qr_url
     *
     * @return the value of t_qr.qr_url
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getQrUrl() {
        return qrUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qr.qr_url
     *
     * @param qrUrl the value for t_qr.qr_url
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setQrUrl(String qrUrl) {
        this.qrUrl = qrUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qr.qr_describe
     *
     * @return the value of t_qr.qr_describe
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getQrDescribe() {
        return qrDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qr.qr_describe
     *
     * @param qrDescribe the value for t_qr.qr_describe
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setQrDescribe(String qrDescribe) {
        this.qrDescribe = qrDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qr.age_range
     *
     * @return the value of t_qr.age_range
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getAgeRange() {
        return ageRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qr.age_range
     *
     * @param ageRange the value for t_qr.age_range
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setAgeRange(String ageRange) {
        this.ageRange = ageRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qr.user_no
     *
     * @return the value of t_qr.user_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qr.user_no
     *
     * @param userNo the value for t_qr.user_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qr.disennable
     *
     * @return the value of t_qr.disennable
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getDisennable() {
        return disennable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qr.disennable
     *
     * @param disennable the value for t_qr.disennable
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setDisennable(String disennable) {
        this.disennable = disennable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qr.sex
     *
     * @return the value of t_qr.sex
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qr.sex
     *
     * @param sex the value for t_qr.sex
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }
}