package com.xiaoweixin.dto;

public class TQrCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qr_code.id
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qr_code.qr_code
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    private String qrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qr_code.qr_url
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    private String qrUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qr_code.qr_describe
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    private String qrDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qr_code.sex
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qr_code.age_range
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    private String ageRange;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qr_code.id
     *
     * @return the value of t_qr_code.id
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qr_code.id
     *
     * @param id the value for t_qr_code.id
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qr_code.qr_code
     *
     * @return the value of t_qr_code.qr_code
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    public String getQrCode() {
        return qrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qr_code.qr_code
     *
     * @param qrCode the value for t_qr_code.qr_code
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    public void setQrCode(String qrCode) {
        this.qrCode = qrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qr_code.qr_url
     *
     * @return the value of t_qr_code.qr_url
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    public String getQrUrl() {
        return qrUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qr_code.qr_url
     *
     * @param qrUrl the value for t_qr_code.qr_url
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    public void setQrUrl(String qrUrl) {
        this.qrUrl = qrUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qr_code.qr_describe
     *
     * @return the value of t_qr_code.qr_describe
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    public String getQrDescribe() {
        return qrDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qr_code.qr_describe
     *
     * @param qrDescribe the value for t_qr_code.qr_describe
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    public void setQrDescribe(String qrDescribe) {
        this.qrDescribe = qrDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qr_code.sex
     *
     * @return the value of t_qr_code.sex
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qr_code.sex
     *
     * @param sex the value for t_qr_code.sex
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qr_code.age_range
     *
     * @return the value of t_qr_code.age_range
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    public String getAgeRange() {
        return ageRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qr_code.age_range
     *
     * @param ageRange the value for t_qr_code.age_range
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    public void setAgeRange(String ageRange) {
        this.ageRange = ageRange;
    }
}