package com.xiaoweixin.dto;

import java.util.ArrayList;
import java.util.List;

public class TQrExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public TQrExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNoIsNull() {
            addCriterion("no is null");
            return (Criteria) this;
        }

        public Criteria andNoIsNotNull() {
            addCriterion("no is not null");
            return (Criteria) this;
        }

        public Criteria andNoEqualTo(String value) {
            addCriterion("no =", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotEqualTo(String value) {
            addCriterion("no <>", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThan(String value) {
            addCriterion("no >", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThanOrEqualTo(String value) {
            addCriterion("no >=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThan(String value) {
            addCriterion("no <", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThanOrEqualTo(String value) {
            addCriterion("no <=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLike(String value) {
            addCriterion("no like", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotLike(String value) {
            addCriterion("no not like", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoIn(List<String> values) {
            addCriterion("no in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotIn(List<String> values) {
            addCriterion("no not in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoBetween(String value1, String value2) {
            addCriterion("no between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotBetween(String value1, String value2) {
            addCriterion("no not between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andQrUrlIsNull() {
            addCriterion("qr_url is null");
            return (Criteria) this;
        }

        public Criteria andQrUrlIsNotNull() {
            addCriterion("qr_url is not null");
            return (Criteria) this;
        }

        public Criteria andQrUrlEqualTo(String value) {
            addCriterion("qr_url =", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlNotEqualTo(String value) {
            addCriterion("qr_url <>", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlGreaterThan(String value) {
            addCriterion("qr_url >", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlGreaterThanOrEqualTo(String value) {
            addCriterion("qr_url >=", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlLessThan(String value) {
            addCriterion("qr_url <", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlLessThanOrEqualTo(String value) {
            addCriterion("qr_url <=", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlLike(String value) {
            addCriterion("qr_url like", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlNotLike(String value) {
            addCriterion("qr_url not like", value, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlIn(List<String> values) {
            addCriterion("qr_url in", values, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlNotIn(List<String> values) {
            addCriterion("qr_url not in", values, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlBetween(String value1, String value2) {
            addCriterion("qr_url between", value1, value2, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrUrlNotBetween(String value1, String value2) {
            addCriterion("qr_url not between", value1, value2, "qrUrl");
            return (Criteria) this;
        }

        public Criteria andQrDescribeIsNull() {
            addCriterion("qr_describe is null");
            return (Criteria) this;
        }

        public Criteria andQrDescribeIsNotNull() {
            addCriterion("qr_describe is not null");
            return (Criteria) this;
        }

        public Criteria andQrDescribeEqualTo(String value) {
            addCriterion("qr_describe =", value, "qrDescribe");
            return (Criteria) this;
        }

        public Criteria andQrDescribeNotEqualTo(String value) {
            addCriterion("qr_describe <>", value, "qrDescribe");
            return (Criteria) this;
        }

        public Criteria andQrDescribeGreaterThan(String value) {
            addCriterion("qr_describe >", value, "qrDescribe");
            return (Criteria) this;
        }

        public Criteria andQrDescribeGreaterThanOrEqualTo(String value) {
            addCriterion("qr_describe >=", value, "qrDescribe");
            return (Criteria) this;
        }

        public Criteria andQrDescribeLessThan(String value) {
            addCriterion("qr_describe <", value, "qrDescribe");
            return (Criteria) this;
        }

        public Criteria andQrDescribeLessThanOrEqualTo(String value) {
            addCriterion("qr_describe <=", value, "qrDescribe");
            return (Criteria) this;
        }

        public Criteria andQrDescribeLike(String value) {
            addCriterion("qr_describe like", value, "qrDescribe");
            return (Criteria) this;
        }

        public Criteria andQrDescribeNotLike(String value) {
            addCriterion("qr_describe not like", value, "qrDescribe");
            return (Criteria) this;
        }

        public Criteria andQrDescribeIn(List<String> values) {
            addCriterion("qr_describe in", values, "qrDescribe");
            return (Criteria) this;
        }

        public Criteria andQrDescribeNotIn(List<String> values) {
            addCriterion("qr_describe not in", values, "qrDescribe");
            return (Criteria) this;
        }

        public Criteria andQrDescribeBetween(String value1, String value2) {
            addCriterion("qr_describe between", value1, value2, "qrDescribe");
            return (Criteria) this;
        }

        public Criteria andQrDescribeNotBetween(String value1, String value2) {
            addCriterion("qr_describe not between", value1, value2, "qrDescribe");
            return (Criteria) this;
        }

        public Criteria andAgeRangeIsNull() {
            addCriterion("age_range is null");
            return (Criteria) this;
        }

        public Criteria andAgeRangeIsNotNull() {
            addCriterion("age_range is not null");
            return (Criteria) this;
        }

        public Criteria andAgeRangeEqualTo(String value) {
            addCriterion("age_range =", value, "ageRange");
            return (Criteria) this;
        }

        public Criteria andAgeRangeNotEqualTo(String value) {
            addCriterion("age_range <>", value, "ageRange");
            return (Criteria) this;
        }

        public Criteria andAgeRangeGreaterThan(String value) {
            addCriterion("age_range >", value, "ageRange");
            return (Criteria) this;
        }

        public Criteria andAgeRangeGreaterThanOrEqualTo(String value) {
            addCriterion("age_range >=", value, "ageRange");
            return (Criteria) this;
        }

        public Criteria andAgeRangeLessThan(String value) {
            addCriterion("age_range <", value, "ageRange");
            return (Criteria) this;
        }

        public Criteria andAgeRangeLessThanOrEqualTo(String value) {
            addCriterion("age_range <=", value, "ageRange");
            return (Criteria) this;
        }

        public Criteria andAgeRangeLike(String value) {
            addCriterion("age_range like", value, "ageRange");
            return (Criteria) this;
        }

        public Criteria andAgeRangeNotLike(String value) {
            addCriterion("age_range not like", value, "ageRange");
            return (Criteria) this;
        }

        public Criteria andAgeRangeIn(List<String> values) {
            addCriterion("age_range in", values, "ageRange");
            return (Criteria) this;
        }

        public Criteria andAgeRangeNotIn(List<String> values) {
            addCriterion("age_range not in", values, "ageRange");
            return (Criteria) this;
        }

        public Criteria andAgeRangeBetween(String value1, String value2) {
            addCriterion("age_range between", value1, value2, "ageRange");
            return (Criteria) this;
        }

        public Criteria andAgeRangeNotBetween(String value1, String value2) {
            addCriterion("age_range not between", value1, value2, "ageRange");
            return (Criteria) this;
        }

        public Criteria andUserNoIsNull() {
            addCriterion("user_no is null");
            return (Criteria) this;
        }

        public Criteria andUserNoIsNotNull() {
            addCriterion("user_no is not null");
            return (Criteria) this;
        }

        public Criteria andUserNoEqualTo(String value) {
            addCriterion("user_no =", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotEqualTo(String value) {
            addCriterion("user_no <>", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoGreaterThan(String value) {
            addCriterion("user_no >", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoGreaterThanOrEqualTo(String value) {
            addCriterion("user_no >=", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLessThan(String value) {
            addCriterion("user_no <", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLessThanOrEqualTo(String value) {
            addCriterion("user_no <=", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLike(String value) {
            addCriterion("user_no like", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotLike(String value) {
            addCriterion("user_no not like", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoIn(List<String> values) {
            addCriterion("user_no in", values, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotIn(List<String> values) {
            addCriterion("user_no not in", values, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoBetween(String value1, String value2) {
            addCriterion("user_no between", value1, value2, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotBetween(String value1, String value2) {
            addCriterion("user_no not between", value1, value2, "userNo");
            return (Criteria) this;
        }

        public Criteria andDisennableIsNull() {
            addCriterion("disennable is null");
            return (Criteria) this;
        }

        public Criteria andDisennableIsNotNull() {
            addCriterion("disennable is not null");
            return (Criteria) this;
        }

        public Criteria andDisennableEqualTo(String value) {
            addCriterion("disennable =", value, "disennable");
            return (Criteria) this;
        }

        public Criteria andDisennableNotEqualTo(String value) {
            addCriterion("disennable <>", value, "disennable");
            return (Criteria) this;
        }

        public Criteria andDisennableGreaterThan(String value) {
            addCriterion("disennable >", value, "disennable");
            return (Criteria) this;
        }

        public Criteria andDisennableGreaterThanOrEqualTo(String value) {
            addCriterion("disennable >=", value, "disennable");
            return (Criteria) this;
        }

        public Criteria andDisennableLessThan(String value) {
            addCriterion("disennable <", value, "disennable");
            return (Criteria) this;
        }

        public Criteria andDisennableLessThanOrEqualTo(String value) {
            addCriterion("disennable <=", value, "disennable");
            return (Criteria) this;
        }

        public Criteria andDisennableLike(String value) {
            addCriterion("disennable like", value, "disennable");
            return (Criteria) this;
        }

        public Criteria andDisennableNotLike(String value) {
            addCriterion("disennable not like", value, "disennable");
            return (Criteria) this;
        }

        public Criteria andDisennableIn(List<String> values) {
            addCriterion("disennable in", values, "disennable");
            return (Criteria) this;
        }

        public Criteria andDisennableNotIn(List<String> values) {
            addCriterion("disennable not in", values, "disennable");
            return (Criteria) this;
        }

        public Criteria andDisennableBetween(String value1, String value2) {
            addCriterion("disennable between", value1, value2, "disennable");
            return (Criteria) this;
        }

        public Criteria andDisennableNotBetween(String value1, String value2) {
            addCriterion("disennable not between", value1, value2, "disennable");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_qr
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 01 16:42:11 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}