package com.xiaoweixin.dto;

import java.util.Date;

public class TRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role_name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.order_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.description
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.no
     *
     * @return the value of t_role.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.no
     *
     * @param no the value for t_role.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role_name
     *
     * @return the value of t_role.role_name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role_name
     *
     * @param roleName the value for t_role.role_name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.order_no
     *
     * @return the value of t_role.order_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.order_no
     *
     * @param orderNo the value for t_role.order_no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.description
     *
     * @return the value of t_role.description
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.description
     *
     * @param description the value for t_role.description
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.create_time
     *
     * @return the value of t_role.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.create_time
     *
     * @param createTime the value for t_role.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.modify_time
     *
     * @return the value of t_role.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.modify_time
     *
     * @param modifyTime the value for t_role.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.is_del
     *
     * @return the value of t_role.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.is_del
     *
     * @param isDel the value for t_role.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}