package com.xiaoweixin.dto;

import java.util.Date;

public class TUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.org_code
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.age
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.birthday
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.img_url
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone_hide
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String phoneHide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.weixin_code
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String weixinCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.weixin_code_hide
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String weixinCodeHide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.img_url_hide
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    private String imgUrlHide;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.no
     *
     * @return the value of t_user.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.no
     *
     * @param no the value for t_user.no
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.org_code
     *
     * @return the value of t_user.org_code
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.org_code
     *
     * @param orgCode the value for t_user.org_code
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.name
     *
     * @return the value of t_user.name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.name
     *
     * @param name the value for t_user.name
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.age
     *
     * @return the value of t_user.age
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.age
     *
     * @param age the value for t_user.age
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.birthday
     *
     * @return the value of t_user.birthday
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.birthday
     *
     * @param birthday the value for t_user.birthday
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.create_time
     *
     * @return the value of t_user.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.create_time
     *
     * @param createTime the value for t_user.create_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.modify_time
     *
     * @return the value of t_user.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.modify_time
     *
     * @param modifyTime the value for t_user.modify_time
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.is_del
     *
     * @return the value of t_user.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.is_del
     *
     * @param isDel the value for t_user.is_del
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.img_url
     *
     * @return the value of t_user.img_url
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.img_url
     *
     * @param imgUrl the value for t_user.img_url
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone
     *
     * @return the value of t_user.phone
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone
     *
     * @param phone the value for t_user.phone
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone_hide
     *
     * @return the value of t_user.phone_hide
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getPhoneHide() {
        return phoneHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone_hide
     *
     * @param phoneHide the value for t_user.phone_hide
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setPhoneHide(String phoneHide) {
        this.phoneHide = phoneHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.weixin_code
     *
     * @return the value of t_user.weixin_code
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getWeixinCode() {
        return weixinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.weixin_code
     *
     * @param weixinCode the value for t_user.weixin_code
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setWeixinCode(String weixinCode) {
        this.weixinCode = weixinCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.weixin_code_hide
     *
     * @return the value of t_user.weixin_code_hide
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getWeixinCodeHide() {
        return weixinCodeHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.weixin_code_hide
     *
     * @param weixinCodeHide the value for t_user.weixin_code_hide
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setWeixinCodeHide(String weixinCodeHide) {
        this.weixinCodeHide = weixinCodeHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.img_url_hide
     *
     * @return the value of t_user.img_url_hide
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public String getImgUrlHide() {
        return imgUrlHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.img_url_hide
     *
     * @param imgUrlHide the value for t_user.img_url_hide
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    public void setImgUrlHide(String imgUrlHide) {
        this.imgUrlHide = imgUrlHide;
    }
}