package com.xiaoweixin.repository;

import com.xiaoweixin.dto.TDict;
import com.xiaoweixin.dto.TDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int countByExample(TDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int deleteByExample(TDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int insert(TDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int insertSelective(TDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    List<TDict> selectByExample(TDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    TDict selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") TDict record, @Param("example") TDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByExample(@Param("record") TDict record, @Param("example") TDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByPrimaryKeySelective(TDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByPrimaryKey(TDict record);
}