package com.xiaoweixin.repository;

import com.xiaoweixin.dto.TFriend;
import com.xiaoweixin.dto.TFriendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int countByExample(TFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int deleteByExample(TFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int insert(TFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int insertSelective(TFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    List<TFriend> selectByExample(TFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    TFriend selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") TFriend record, @Param("example") TFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByExample(@Param("record") TFriend record, @Param("example") TFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByPrimaryKeySelective(TFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByPrimaryKey(TFriend record);
}