package com.xiaoweixin.repository;

import com.xiaoweixin.dto.TQrCode;
import com.xiaoweixin.dto.TQrCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TQrCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr_code
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    int countByExample(TQrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr_code
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    int deleteByExample(TQrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr_code
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr_code
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    int insert(TQrCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr_code
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    int insertSelective(TQrCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr_code
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    List<TQrCode> selectByExample(TQrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr_code
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    TQrCode selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr_code
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    int updateByExampleSelective(@Param("record") TQrCode record, @Param("example") TQrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr_code
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    int updateByExample(@Param("record") TQrCode record, @Param("example") TQrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr_code
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    int updateByPrimaryKeySelective(TQrCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr_code
     *
     * @mbggenerated Mon Aug 28 13:13:16 CST 2017
     */
    int updateByPrimaryKey(TQrCode record);
}