package com.xiaoweixin.repository;

import com.xiaoweixin.dto.TQr;
import com.xiaoweixin.dto.TQrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TQrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int countByExample(TQrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int deleteByExample(TQrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int insert(TQr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int insertSelective(TQr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    List<TQr> selectByExample(TQrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    TQr selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") TQr record, @Param("example") TQrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByExample(@Param("record") TQr record, @Param("example") TQrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByPrimaryKeySelective(TQr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qr
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByPrimaryKey(TQr record);
}