package com.xiaoweixin.repository;

import com.xiaoweixin.dto.TRoleLevel;
import com.xiaoweixin.dto.TRoleLevelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TRoleLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_level
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int countByExample(TRoleLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_level
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int deleteByExample(TRoleLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_level
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_level
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int insert(TRoleLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_level
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int insertSelective(TRoleLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_level
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    List<TRoleLevel> selectByExample(TRoleLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_level
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    TRoleLevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_level
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") TRoleLevel record, @Param("example") TRoleLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_level
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByExample(@Param("record") TRoleLevel record, @Param("example") TRoleLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_level
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByPrimaryKeySelective(TRoleLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_level
     *
     * @mbggenerated Fri Sep 01 16:42:11 CST 2017
     */
    int updateByPrimaryKey(TRoleLevel record);
}